version: '3'

services:

  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres
    environment:
      - POSTGRES_USER=polymny
      - POSTGRES_PASSWORD=polymny
      - POSTGRES_DB=polymny
    ports:
      - 5432
