[package]
name = "server"
version = "0.1.0"
edition = "2018"
default-run = "server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
diesel = { version = "1.4.3", features = ["chrono"] }
rand = "0.7.2"
bcrypt = "0.6.1"
tera = "1.0.1"
lazy_static = "1.4.0"
failure = "0.1.6"
lettre = "0.9.2"
lettre_email = "0.9.2"
chrono = "0.4"
serde = { version = "1.0.44", features = ["derive"] }
serde_yaml = "0.8"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["serve", "diesel_postgres_pool", "json"]

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "populate-db"
path = "src/populate_db.rs"
