name: build
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build-linux:
    name: Polymny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        env:
            TZ: Antartica/Troll
            DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends git clang curl pkg-config libssl-dev libpq-dev
      - uses: polymny/setup-elm@ee2fb83b65e2506c84aea6942092491feccd876a
        name : Set up Elm
        with:
          elm-version: 0.19.1
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          toolchain: stable
          override: true
      - name : Build client
        run: |
          cargo install --git https://github.com/polymny/potoelm && potoelm client/strings/ > client/src/Strings.elm && cd client && elm make src/Main.elm
      - name: Build server
        run: |
          cd server && cargo build --no-default-features
